name: Get Unity License Request (.alf)

on: workflow_dispatch # Запускаем вручную с айфона

jobs:
  get_alf:
    runs-on: ubuntu-latest
    steps:
      - name: Request License File
        uses: game-ci/unity-request-activation-file@v4
        with:
          unityVersion: 2022.3.11f1 # Указываем версию Unity для порта (можно менять)
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Unity-Activation-File
          path: ./*.alf
